services:
  # 1. OpenTelemetry Collector (The Data Router)
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.118.0
    container_name: otel-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./config/otel-collector.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    networks:
      - sihibank-network
    depends_on:
      - prometheus
      - loki
      - tempo

  # 2. Prometheus (Metrics Server - Limited to 512MB / 24h)
  # 2. Prometheus (Metrics Server - Limited to 512MB / 24h)
  prometheus:
    image: prom/prometheus:v3.14.0
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=otlp-write-receiver     # Add this: Native OpenTelemetry ingestion engine
      - --storage.tsdb.retention.time=24h
      - --storage.tsdb.retention.size=512MB
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - sihibank-network


  # 3. Grafana Loki (Logs Server - Limited to 24h)
  loki:
    image: grafana/loki:3.3.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - sihibank-network

  # 4. Grafana Tempo (Traces Server - Limited to 512MB / 24h)
  tempo:
    image: grafana/tempo:2.7.0
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"
    networks:
      - sihibank-network

  # 5. Grafana UI (The Monitoring Hub)
  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    # --- ADD THIS VOLUMES BLOCK TO MOUNT THE AUTOMATED CONFIGS ---
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - sihibank-network
    depends_on:
      - prometheus
      - loki
      - tempo

  # 6. MinIO (Local Amazon S3 Simulator - Explicitly Version Pinned)
  minio:
    image: alpine/minio:RELEASE.2025-10-15T17-29-55Z
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # MinIO S3 API Endpoint
      - "9001:9001" # Web UI Console Access
    environment:
      MINIO_ROOT_USER: sihibank-admin
      MINIO_ROOT_PASSWORD: sihibank-secure-password
    networks:
      - sihibank-network



networks:
  sihibank-network:
    name: sihibank-network # Automatically creates the network on your MacBook Pro if it does not exist
